### ISSUE TITLE
igbp class file

### ISSUE THREAD

**Issue by martaddi** [jschap1/vicglobal-prep#2]
Hi,
i am using your script to prepare a vegetation parameter file. Can i get this file
" igbp_classnames.txt"

**Comment by jschap1** [comment]
It has been uploaded. Let me know if there are further files that are needed.

**Comment by martaddi** [comment]
Thank you
----


 

    On Sunday, May 21, 2023 at 05:44:48 PM GMT+1, Jacob ***@***.***> wrote:  
 
 


It has been uploaded. Let me know if there are further files that are needed. I don't think anyone besides me has run this code before (and I have not looked at it in a couple years).

**Comment by martaddi** [comment]
Thank you

**Comment by martaddi** [comment]
Hello,I want to calibrate Vic and chanced on your calVic script but some input data are not in the source code e.g. '/home/jschap/Documents/ESSD/lumped_cal/sceua/wb_39.24321_-109.02250.txt' and /hdd/ESSD/data/naturalized_flow_usgs_09380000.txt
I would be glad if you can share with me and any possible Vic model calibration tools for streamflow.Thanks.
----

 

    On Sunday, May 21, 2023 at 05:44:48 PM GMT+1, Jacob ***@***.***> wrote:  
 
 


It has been uploaded. Let me know if there are further files that are needed. I don't think anyone besides me has run this code before (and I have not looked at it in a couple years).

**Comment by jschap1** [comment]
Hi Marta, 

I have uploaded those two files as examples of what the water balance (wb) output files from VIC and the streamflow data should look like, but you would need to obtain streamflow for your basin and use your VIC setup to generate the wb files. The idea is, you run VIC with a baseline set of parameters, read in the outputs, route the runoff+baseflow to the gauges, and calibrate the parameters to get the best fit between the predicted and actual streamflow. I've used the SCE-UA and DDS algorithms for this, although there are others. You should be able to find codes to implement those online (I used the MATLAB file exchange).

Jacob

**Comment by martaddi** [comment]
Thanks for the feedback. what units are your streamflow?
----
 

    On Saturday, July 1, 2023 at 03:33:31 PM GMT+1, Jacob ***@***.***> wrote:  
 
 


Hi Marta,

I have uploaded those two files as examples of what the water balance (wb) output files from VIC and the streamflow data should look like, but you would need to obtain streamflow for your basin and use your VIC setup to generate the wb files. The idea is, you run VIC with a baseline set of parameters, read in the outputs, route the runoff+baseflow to the gauges, and calibrate the parameters to get the best fit between the predicted and actual streamflow. I've used the SCE-UA and DDS algorithms for this, although there are others. You should be able to find codes to implement those online (I used the MATLAB file exchange).

Jacob

**Comment by jschap1** [comment]
The units should be in the header row of the naturalized_flow_* text file.

**Comment by martaddi** [comment]
I tried the script ucrb_calvic_wrapper.m  and it gives the same KGE values for each iteration. I guess i am doing some wrong. Any suggestion on might be going wrong?

 

    On Sunday, July 2, 2023 at 06:33:33 PM GMT+1, Jacob ***@***.***> wrote:  
 
 


The units should be in the header row of the naturalized_flow_* text file.

**Comment by martaddi** [comment]
Please can you share with me the  route_1.0 set-up. RVIC is what available on UW  VIC site. Thanks 
---- 

    On Thursday, July 6, 2023 at 07:04:27 PM GMT+1, Addi Martin ***@***.***> wrote:  
 
 I tried the script ucrb_calvic_wrapper.m  and it gives the same KGE values for each iteration. I guess i am doing some wrong. Any suggestion on might be going wrong?

 

    On Sunday, July 2, 2023 at 06:33:33 PM GMT+1, Jacob ***@***.***> wrote:  
 
 


The units should be in the header row of the naturalized_flow_* text file.

**Comment by jschap1** [comment]
Hi Marta, sorry for the delayed reply. The route_1.0 routing model is the Lohmann (1999) routing model that is commonly used with VIC. The version I used is written in Fortran. You can find it here: https://github.com/UW-Hydro/VIC_Routing

If you are getting the same KGE values each time, then the parameters are not changing each time you run the simulation. Is your soil parameter file being updated after each iteration of the optimization algorithm?

**Comment by martaddi** [comment]
Thanks for the feedback. Have install the route_1.0 but seem the site doesn't have much on wiki. Can you share with me the rout_param.txt to have a fair idea how to set the routing then  i will run the run_sceua.m file.


    On Thursday, July 13, 2023 at 12:17:05 AM GMT+1, Jacob ***@***.***> wrote:  
 
 


Hi Marta, sorry for the delayed reply. The route_1.0 routing model is the Lohmann (1999) routing model that is commonly used with VIC. The version I used is written in Fortran. You can find it here: https://github.com/UW-Hydro/VIC_Routing

If you are getting the same KGE values each time, then the parameters are not changing each time you run the simulation. Is your soil parameter file being updated after each iteration of the optimization algorithm?

**Comment by jschap1** [comment]
I have added a sample rout_param.txt file to the repository. Hopefully this should give you an idea of how to set up the routing model parameter file. If you would like to speak further about this, feel free to send me an email at jschap@g.ucla.edu, and we can set up a Zoom call.
